### ISSUE TITLE
То, что используется из разных потоков неплохо бы делать volatile

### ISSUE THREAD

**Issue by coursar** [BigArtemka/server-framework#1]
https://github.com/BigArtemka/server-framework/blob/57a35f84dd0f7b9049373fe0fe31b11e832e9d62/src/main/java/ru/filimonov/framework/Server.java#L77

**Comment by BigArtemka** [comment]
https://github.com/BigArtemka/server-framework/blob/d1057471fcbb1991571be4e66ad07ff20fdc52ea/src/main/java/ru/filimonov/framework/Server.java#L77
Сделал.
