### ISSUE TITLE
А где кладётся форма?

### ISSUE THREAD

**Issue by coursar** [BigArtemka/server-framework#5]
https://github.com/BigArtemka/server-framework/blob/57a35f84dd0f7b9049373fe0fe31b11e832e9d62/src/main/java/ru/filimonov/framework/Server.java#L240-L245

**Comment by BigArtemka** [comment]
https://github.com/BigArtemka/server-framework/blob/d1057471fcbb1991571be4e66ad07ff20fdc52ea/src/main/java/ru/filimonov/framework/Server.java#L241-L248
Исправил

**Comment by coursar** [comment]
Надо закрывать issue сообщениями коммита, а не руками
